// The accurate 2025/2026 GOUNI Faculty and Department Mappings
export const facultyData: Record<string, string[]> = {
  "Management & Social Sciences": [
    "Accounting",
    "Banking and Finance",
    "Management",
    "Marketing",
    "Public Administration",
    "Economics",
    "Political Science",
    "International Relations",
    "Mass Communications",
    "Philosophy",
    "Psychology",
    "Religious Studies",
    "Sociology",
  ],
  "Natural Sciences & Env. Studies": [
    "Applied Biology",
    "Biotechnology",
    "Microbiology",
    "Chemistry",
    "Biochemistry",
    "Industrial Chemistry",
    "Physics",
    "Architecture",
    "Industrial Design",
  ],
  "Computing and Info. Tech": [
    "Computer Science",
    "Mathematics",
    "Statistics & Demography",
  ],
  Education: [
    "Biology Education",
    "Chemistry Education",
    "Mathematics Education",
    "Physics Education",
    "English & Lit Studies Edu",
    "History/Int. Studies Edu",
    "Economics Education",
    "Political Sci. & Govt. Edu",
    "Social Studies Edu",
    "Business Education",
    "Computer Science Edu",
  ],
  Arts: [
    "History, Int Rel. & Diplomacy",
    "Music",
    "English and Lit Studies",
    "Philosophy",
  ],
  Law: ["Juris & Int'l Law", "Public Law", "Private & Biz Law"],
  "Clinical Medicine": ["Medicine and Surgery", "Nursing Sciences"],
};
